apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-deployment
  labels:
    app: udacity
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udacity
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: udacity
    spec:
      containers:
      - name: udacity
        image: xuren71/devops-capstone
        ports:
        - containerPort: 80
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            scheme: HTTP
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1